function A = frame_transformation(a,alpha,d,theta)
%FRAME_TRANSFORMATION
%    A = FRAME_TRANSFORMATION(A,ALPHA,D,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    07-Nov-2019 20:22:42

t2 = cos(alpha);
t3 = sin(alpha);
t4 = cos(theta);
t5 = sin(theta);
A = reshape([t4,t5,0.0,0.0,-t2.*t5,t2.*t4,t3,0.0,t3.*t5,-t3.*t4,t2,0.0,a.*t4,a.*t5,d,1.0],[4,4]);
